"""
deep_notes_ai/services/markdown/markdown_parser_service.py

MarkdownParserService — reconstruct Node hierarchy and content store
from a markdown document generated by MarkdownService.
"""

from __future__ import annotations

import logging
import uuid

from deep_notes_ai.domain.models import (
    ContentNode,
    ContentStoreItem,
    Node,
    TitleNode,
)

logger = logging.getLogger(__name__)


class MarkdownParserService:
    """
    Parse a markdown document and reconstruct a Node hierarchy and content
    store.

    Assumptions:
    - Any markdown heading (# through ######) represents a TitleNode.
    - The first heading is NOT treated specially; it becomes a normal TitleNode.
    - Heading levels determine hierarchy.
    - Any markdown content between two headings belongs to the preceding
      TitleNode as a ContentNode.
    - The original document title is intentionally ignored.
    """

    def parse_document(
        self,
        markdown: str,
    ) -> tuple[list[Node], dict[str, ContentStoreItem]]:
        """
        Parse markdown into hierarchy and content store.

        Args:
            markdown:
                Complete markdown document.

        Returns:
            (
                hierarchy,
                content_store,
            )
        """
        lines = markdown.splitlines()

        hierarchy: list[Node] = []
        content_store: dict[str, ContentStoreItem] = {}

        stack: list[tuple[int, TitleNode]] = []

        current_heading: TitleNode | None = None
        current_content: list[str] = []

        def flush_content() -> None:
            """
            Persist accumulated markdown content under the current heading.
            """
            nonlocal current_content

            if current_heading is None:
                current_content = []
                return

            text = "\n".join(current_content).strip()

            if not text:
                current_content = []
                return

            content_id = str(uuid.uuid4())

            content_store[content_id] = ContentStoreItem(
                content=text,
                summary="",
            )

            current_heading.subtopics.append(
                ContentNode(
                    id=content_id,
                )
            )

            current_content = []

        for raw_line in lines:
            line = raw_line.rstrip()

            if self._is_heading(line):
                flush_content()

                heading_level = self._heading_level(line)
                heading_text = line[heading_level:].strip()

                node = TitleNode(
                    name=heading_text,
                    subtopics=[],
                )

                while stack and stack[-1][0] >= heading_level:
                    stack.pop()

                if stack:
                    stack[-1][1].subtopics.append(node)
                else:
                    hierarchy.append(node)

                stack.append((heading_level, node))
                current_heading = node
                continue

            current_content.append(raw_line)

        flush_content()

        return (
            hierarchy,
            content_store,
        )

    def _is_heading(
        self,
        line: str,
    ) -> bool:
        """
        Return True if the line is a valid ATX markdown heading.
        """
        stripped = line.lstrip()

        if not stripped.startswith("#"):
            return False

        level = self._heading_level(stripped)

        if level == 0 or level > 6:
            return False

        return len(stripped) > level and stripped[level] == " "

    def _heading_level(
        self,
        line: str,
    ) -> int:
        """
        Return the markdown heading level (1-6).
        """
        level = 0

        for char in line.lstrip():
            if char == "#":
                level += 1
            else:
                break

        return min(level, 6)